---
title: "Anova"
author: "R.M. Palmer"
date: "11/21/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(devtools)
library(ggpubr)
```

```{r child = 'dataload.Rmd'}
```

```{r anova_prep}
for_anova <- employee_data %>%
  mutate(numeric_attrition = as.numeric(Attrition))
```

```{r anova_groups}
anova_qc_1 <- function(varname)
{
  # group and summarise
  index <- which(colnames(for_anova)==varname)
  subset_df <- for_anova %>% select(MonthlyIncome,index)
  colnames(subset_df) <- c("MonthlyIncome","x")
  subset_df %>% group_by(x) %>%
    summarise(
      count=n(),
      mean=mean(MonthlyIncome),
      sd=sd(MonthlyIncome)
    )
}
anova_qc_2 <- function(varname)
{
  # box plot
  ggboxplot(for_anova,x=varname,y="MonthlyIncome",
          color=varname,ylab="MonthlyIncome",xlab=varname)
}
anova_qc_3 <- function(varname)
{
  # anova
  formula <- as.formula(paste("MonthlyIncome",varname,sep=" ~ "))
  res.aov <- aov(formula, data = for_anova)
  summary(res.aov)
}
anova_qc_4 <- function(varname)
{
  # anova
  formula <- as.formula(paste("numeric_attrition",varname,sep=" ~ "))
  res.aov <- aov(formula, data = for_anova)
  summary(res.aov)
}

```

```{r}
anova_qc_1('BusinessTravel')
anova_qc_2('BusinessTravel')
anova_qc_3('BusinessTravel')
anova_qc_4('BusinessTravel')
```

```{r}
anova_qc_1('YearsSinceLastPromotion')
anova_qc_2('YearsSinceLastPromotion')
anova_qc_3('YearsSinceLastPromotion')
anova_qc_4('YearsSinceLastPromotion')
```
```{r}
anova_qc_1('YearsWithCurrManager')
anova_qc_2('YearsWithCurrManager')
anova_qc_3('YearsWithCurrManager')
anova_qc_4('YearsWithCurrManager')
```
```{r}
anova_qc_1('YearsAtCompany')
anova_qc_2('YearsAtCompany')
anova_qc_3('YearsAtCompany')
anova_qc_4('YearsAtCompany')
```
```{r}
anova_qc_1('TotalWorkingYears')
anova_qc_2('TotalWorkingYears')
anova_qc_3('TotalWorkingYears')
anova_qc_4('TotalWorkingYears')
```
```{r}
anova_qc_1('JobLevel')
anova_qc_2('JobLevel')
anova_qc_3('JobLevel')
anova_qc_4('JobLevel')
```
```{r}
anova_qc_1('Education')
anova_qc_2('Education')
anova_qc_3('Education')
anova_qc_4('Education')
```
```{r}
anova_qc_1('DistanceFromHome')
anova_qc_2('DistanceFromHome')
anova_qc_3('DistanceFromHome')
anova_qc_4('DistanceFromHome')
```
```{r}
anova_qc_1('Age')
anova_qc_2('Age')
anova_qc_3('Age')
anova_qc_4('Age')
```
```{r}
anova_qc_1('WorkLifeBalance')
anova_qc_2('WorkLifeBalance')
anova_qc_3('WorkLifeBalance')
anova_qc_4('WorkLifeBalance')
```
```{r}
anova_qc_1('TrainingTimesLastYear')
anova_qc_2('TrainingTimesLastYear')
anova_qc_3('TrainingTimesLastYear')
anova_qc_4('TrainingTimesLastYear')
```
```{r}
anova_qc_1('StockOptionLevel')
anova_qc_2('StockOptionLevel')
anova_qc_3('StockOptionLevel')
anova_qc_4('StockOptionLevel')
```
```{r}
anova_qc_1('RelationshipSatisfaction')
anova_qc_2('RelationshipSatisfaction')
anova_qc_3('RelationshipSatisfaction')
anova_qc_4('RelationshipSatisfaction')
```
```{r}
anova_qc_1('PerformanceRating')
anova_qc_2('PerformanceRating')
anova_qc_3('PerformanceRating')
anova_qc_4('PerformanceRating')
```
```{r}
anova_qc_1('PercentSalaryHike')
anova_qc_2('PercentSalaryHike')
anova_qc_3('PercentSalaryHike')
anova_qc_4('PercentSalaryHike')
```
```{r}
anova_qc_1('NumCompaniesWorked')
anova_qc_2('NumCompaniesWorked')
anova_qc_3('NumCompaniesWorked')
anova_qc_4('NumCompaniesWorked')
```
```{r}
anova_qc_1('JobSatisfaction')
anova_qc_2('JobSatisfaction')
anova_qc_3('JobSatisfaction')
anova_qc_4('JobSatisfaction')
```
```{r}
anova_qc_1('JobInvolvement')
anova_qc_2('JobInvolvement')
anova_qc_3('JobInvolvement')
anova_qc_4('JobInvolvement')
```
```{r}
anova_qc_1('EnvironmentSatisfaction')
anova_qc_2('EnvironmentSatisfaction')
anova_qc_3('EnvironmentSatisfaction')
anova_qc_4('EnvironmentSatisfaction')
```



