---
title: "DataLoad"
author: "R.M. Palmer"
date: "11/15/2019"
output: html_document
---

```{r dataload, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


```{r import_csv}
# import raw data
train_raw <- read.csv('CaseStudy2-data.csv') 

# 1) drop unused columns
# 2) transform numeric columns
#    some of the columns are log(value+1) to avoid log of zero...
employee_data <- train_raw %>% select(-Over18,
                                      -EmployeeNumber,
                                      -EmployeeCount,
                                      -DailyRate,
                                      -MonthlyRate,
                                      -HourlyRate,
                                      -StandardHours) %>%
  mutate(t_DistanceFromHome = log(DistanceFromHome),
         t_Education = Education,
         t_EnvironmentSatisfaction = EnvironmentSatisfaction,
         t_JobInvolvement = JobInvolvement,
         t_JobLevel = JobLevel,
         t_JobSatisfaction = JobSatisfaction,
         t_NumCompaniesWorked = NumCompaniesWorked,
         t_PercentSalaryHike = PercentSalaryHike,
         t_PerformanceRating = PerformanceRating,
         t_RelationshipSatisfaction = RelationshipSatisfaction,
         t_StockOptionLevel = StockOptionLevel,
         t_TotalWorkingYears = sqrt(TotalWorkingYears),
         t_TrainingTimesLastYear = TrainingTimesLastYear,
         t_WorkLifeBalance = WorkLifeBalance,
         t_YearsAtCompany = log(YearsAtCompany+1),
         t_YearsInCurrentRole = log(YearsInCurrentRole+1),
         t_YearsSinceLastPromotion = YearsSinceLastPromotion,
         t_YearsWithCurrManager = log(YearsWithCurrManager+1))
	 
# these are constant:
#  Over18, StandardHours
# these are redundant
#  DailyRate, MonthlyRate, HourlyRate


# identifiying:

# ID
# Attrition
# EmployeeNumber

# Factors:

# BusinessTravel
# Department
# EducationField
# Gender
# JobRole
# MaritalStatus
## Over18
# OverTime


# Numeric:

# Age
# DailyRate
# DistanceFromHome
# Education
# EmployeeCount
# EnvironmentSatisfaction
# HourlyRate

```