---
title: "EDA"
author: "R.M. Palmer"
date: "11/15/2019"
output: html_document
---

```{r eda, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(gridExtra)
library(grid)
library(ggplot2)
library(lattice)

```

```{r child = 'dataload.Rmd'}
```

```{r sanity_check}
# check for NA values
train_raw %>% 
  select_if(function(x) any(is.na(x))) %>% 
  summarise_each(funs(sum(is.na(.)))) -> raw_NA
```


```{r crossplot_wage_rates}
# these rates seem to be unrelated to income.
train_raw %>% 
  select(MonthlyIncome,DailyRate,HourlyRate,MonthlyRate) %>% pairs()
```

```{r crossplot_years}
train_raw %>%
  select(YearsAtCompany,
         YearsInCurrentRole,
         YearsSinceLastPromotion,
         YearsWithCurrManager,
         NumCompaniesWorked) %>% pairs()
```

```{r crossplot_education}
train_raw %>% 
  select(Education,
         JobLevel,
         YearsAtCompany) %>% pairs()
```

```{r}
# histogram, distinguished by Attrition, and normalized
attr_hist <- function(varname)
{
  # scale up by this amount to normalize the two histograms
  nbins <- 21
  index_1 <- which(colnames(train_raw)==varname)
  index_2 <- which(colnames(train_raw)=='Attrition')
  two_cols <- train_raw %>% dplyr::select(index_1,index_2)
  colnames(two_cols)  <- c('x','Attrition')
  two_cols %>% ggplot(mapping=aes(x=x,y=..density..)) +
      geom_histogram(bins=nbins) +
      ggtitle(varname) +
      facet_wrap(~Attrition)
}

# histogram of each of the numeric predictors, separated by Attrition
attr_hist('Age')
attr_hist('DistanceFromHome')
attr_hist('MonthlyIncome')
attr_hist('YearsAtCompany')
attr_hist('YearsSinceLastPromotion')
attr_hist('YearsWithCurrManager')
attr_hist('WorkLifeBalance')
attr_hist('TotalWorkingYears')
attr_hist('PerformanceRating')
attr_hist('PercentSalaryHike')
attr_hist('JobLevel')
attr_hist('StockOptionLevel')
attr_hist('Education')
attr_hist('EnvironmentSatisfaction')
attr_hist('JobInvolvement')
attr_hist('JobSatisfaction')
attr_hist('NumCompaniesWorked')
attr_hist('RelationshipSatisfaction')
attr_hist('TrainingTimesLastYear')
attr_hist('WorkLifeBalance')
attr_hist('YearsInCurrentRole')


```

```{r}
# histogram of Monthly Income, broken down by each of the categorical varibles
# BusinessTravel
# Department
# EducationField
# Gender
# JobRole
# MaritalStatus
train_raw %>% ggplot(mapping=aes(x=MonthlyIncome)) +
  geom_histogram() + facet_wrap(~BusinessTravel)
train_raw %>% ggplot(mapping=aes(x=MonthlyIncome)) +
  geom_histogram() + facet_wrap(~Department)

train_raw %>% ggplot(mapping=aes(x=MonthlyIncome)) +
  geom_histogram() + facet_wrap(~EducationField)

train_raw %>% ggplot(mapping=aes(x=MonthlyIncome)) +
  geom_histogram() + facet_wrap(~Gender)

train_raw %>% ggplot(mapping=aes(x=MonthlyIncome)) +
  geom_histogram() + facet_wrap(~JobRole)

train_raw %>% ggplot(mapping=aes(x=MonthlyIncome)) +
  geom_histogram() + facet_wrap(~MaritalStatus)

train_raw %>% ggplot(mapping=aes(x=MonthlyIncome)) +
  geom_histogram() + facet_wrap(~OverTime)

```

## good idea to test statistical significance of the categorical variables


```{r make_histograms}
cuberoot <- function(arg)
{
  return(arg^(1/3))
}
mylog <- function(arg)
{
  return (log(1+arg))
}
noop <- function(arg)
{
  return(arg)
}
myqc <- function(varname,zb=0)
{
  index <- which(colnames(train_raw)==varname)
  nbins <- 21
  one_col <- train_raw %>% select(index)
  colnames(one_col)  <- c('x')
  p1 <- one_col %>% ggplot(aes(x=x)) + geom_histogram(bins=nbins) + ggtitle(varname)
  p2 <- one_col %>% ggplot(aes(sample=x)) + stat_qq() + ggtitle(varname)
  p3 <- one_col %>% mutate(new_value = log(x+zb)) %>%
    ggplot(aes(x=new_value)) + geom_histogram(bins=nbins) + ggtitle(paste('log',varname))
  p4 <- one_col %>% mutate(new_value = log(x+zb)) %>%
    ggplot(aes(sample=new_value)) + stat_qq() + ggtitle(paste('log',varname))
  p5 <- one_col %>% mutate(new_value = sqrt(x+zb)) %>%
    ggplot(aes(x=new_value)) + geom_histogram(bins=nbins) + ggtitle(paste('sqrt',varname))
  p6 <- one_col %>% mutate(new_value = sqrt(x+zb)) %>%
    ggplot(aes(sample=new_value)) + stat_qq() + ggtitle(paste('sqrt',varname))
  grid.arrange(p1,p2,p3,p4,p5,p6,nrow=3)
}

myqc('Age')
myqc('DistanceFromHome')
myqc('MonthlyIncome')
myqc('YearsAtCompany',1)
myqc('YearsSinceLastPromotion',1)
myqc('YearsWithCurrManager',1)
myqc('WorkLifeBalance')
myqc('TotalWorkingYears',1)
myqc('PerformanceRating')
myqc('PercentSalaryHike')
myqc('JobLevel')
myqc('StockOptionLevel',1)
myqc('Education')
myqc('EnvironmentSatisfaction')
myqc('JobInvolvement')
myqc('JobSatisfaction')
myqc('NumCompaniesWorked',1)
myqc('RelationshipSatisfaction')
myqc('TrainingTimesLastYear',1)
myqc('WorkLifeBalance')
myqc('YearsInCurrentRole',1)
```


# tabulate yes and no by categorical variables
```{r}
# tabulate yes and no by categorical variables
employee_data %>%
  group_by(EducationField,Attrition) %>%
  summarise(count=n()) %>%
  spread(Attrition,count) %>% 
  mutate(perc=Yes/No) %>% 
  ggplot(aes(x=EducationField,y=perc)) + 
  geom_bar(stat="identity") +
  ggtitle('Percent Attrition by EducationField')
```

```{r}
# tabulate yes and no by categorical variables
employee_data %>%
  group_by(BusinessTravel,Attrition) %>%
  summarise(count=n()) %>%
  spread(Attrition,count) %>% 
  mutate(perc=Yes/No) %>% 
  ggplot(aes(x=BusinessTravel,y=perc)) + 
  geom_bar(stat="identity") +
  ggtitle('Percent Attrition by BusinessTravel')
```

```{r}
# tabulate yes and no by categorical variables
employee_data %>%
  group_by(Department,Attrition) %>%
  summarise(count=n()) %>%
  spread(Attrition,count) %>% 
  mutate(perc=Yes/No) %>% 
  ggplot(aes(x=Department,y=perc)) + 
  geom_bar(stat="identity") +
  ggtitle('Percent Attrition by Department')
```

```{r}
# tabulate yes and no by categorical variables
employee_data %>%
  group_by(Gender,Attrition) %>%
  summarise(count=n()) %>%
  spread(Attrition,count) %>% 
  mutate(perc=Yes/No) %>% 
  ggplot(aes(x=Gender,y=perc)) + 
  geom_bar(stat="identity") +
  ggtitle('Percent Attrition by Gender')
```

```{r}
# tabulate yes and no by categorical variables
employee_data %>%
  group_by(JobRole,Attrition) %>%
  summarise(count=n()) %>%
  spread(Attrition,count) %>% 
  mutate(perc=Yes/No) %>% 
  ggplot(aes(x=JobRole,y=perc)) + 
  geom_bar(stat="identity") +
  ggtitle('Percent Attrition by JobRole')
```

```{r}
# tabulate yes and no by categorical variables
employee_data %>%
  group_by(MaritalStatus,Attrition) %>%
  summarise(count=n()) %>%
  spread(Attrition,count) %>% 
  mutate(perc=Yes/No) %>% 
  ggplot(aes(x=MaritalStatus,y=perc)) + 
  geom_bar(stat="identity") +
  ggtitle('Percent Attrition by MaritalStatus')
```

