---
title: "K Nearest Neighbors"
author: "R.M. Palmer"
date: "11/18/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r child = 'dataload.Rmd'}
```

```{r}
library(caret)
library(class)
```

```{r prep_for_knn}
normalized <- employee_data %>%
  mutate(z_DistanceFromHome = scale(t_DistanceFromHome),
         z_Education = scale(t_Education),
         z_EnvironmentSatisfaction = scale(t_EnvironmentSatisfaction),
         z_JobInvolvement = scale(t_JobInvolvement),
         z_JobLevel = scale(t_JobLevel),
         z_JobSatisfaction = scale(t_JobSatisfaction),
         z_NumCompaniesWorked = scale(t_NumCompaniesWorked),
         z_PercentSalaryHike = scale(t_PercentSalaryHike),
         z_PerformanceRating = scale(t_PerformanceRating),
         z_RelationshipSatisfaction = scale(t_RelationshipSatisfaction),
         z_StockOptionLevel = scale(t_StockOptionLevel),
         z_TotalWorkingYears = scale(t_TotalWorkingYears),
         z_TrainingTimesLastYear = scale(t_TrainingTimesLastYear),
         z_WorkLifeBalance = scale(t_WorkLifeBalance),
         z_YearsAtCompany = scale(t_YearsAtCompany),
         z_YearsInCurrentRole = scale(t_YearsInCurrentRole),
         z_YearsSinceLastPromotion = scale(t_YearsSinceLastPromotion),
         z_YearsWithCurrManager = scale(t_YearsWithCurrManager)) %>% 
  select(Attrition,
         z_DistanceFromHome,
         z_Education,
         z_EnvironmentSatisfaction,
         z_JobInvolvement,
         z_JobLevel,
         z_JobSatisfaction,
         z_NumCompaniesWorked,
         z_PercentSalaryHike,
         z_PerformanceRating,
         z_RelationshipSatisfaction,
         z_StockOptionLevel,
         z_TotalWorkingYears,
         z_TrainingTimesLastYear,
         z_WorkLifeBalance,
         z_YearsAtCompany,
         z_YearsInCurrentRole,
         z_YearsSinceLastPromotion,
         z_YearsWithCurrManager)
	 
cols_for_knn <- c("z_DistanceFromHome",
         "z_Education",
         "z_EnvironmentSatisfaction",
         "z_JobInvolvement",
         "z_JobLevel",
         "z_JobSatisfaction",
         "z_NumCompaniesWorked",
         "z_PercentSalaryHike",
         "z_PerformanceRating",
         "z_RelationshipSatisfaction",
         "z_StockOptionLevel",
         "z_TotalWorkingYears",
         "z_TrainingTimesLastYear",
         "z_WorkLifeBalance",
         "z_YearsAtCompany",
         "z_YearsInCurrentRole",
         "z_YearsSinceLastPromotion",
         "z_YearsWithCurrManager")

```

```{r knn_parms}
set.seed(42)
train_frac <- 0.7
numks <- 50
knn_trials <- 100
positive_value <- 'Yes'
```

```{r do_knn}
knn_stats = matrix(nrow=numks,ncol=4)
for (i in 1:numks)
{
  acc  = matrix(nrow=knn_trials,ncol=1)
  sens = matrix(nrow=knn_trials,ncol=1)
  spec = matrix(nrow=knn_trials,ncol=1)
  for (j in 1:knn_trials)
  {
    trainIndices = sample(1:dim(normalized)[1],round(train_frac * dim(normalized)[1]))
    trainData = normalized[trainIndices,]
    testData = normalized[-trainIndices,]
    classifications = knn(trainData[,cols_for_knn],
                              testData[,cols_for_knn],
                              trainData$Attrition, prob = TRUE, k = i)
    CM = confusionMatrix(table(testData$Attrition,classifications),positive=positive_value)
    acc[j]  = CM$overall[1]
    sens[j] = CM$byClass[1]
    spec[j] = CM$byClass[2]
  }
  knn_stats[i,1] = i
  knn_stats[i,2] = colMeans(acc,na.rm = TRUE)
  knn_stats[i,3] = colMeans(sens,na.rm = TRUE)
  knn_stats[i,4] = colMeans(spec,na.rm = TRUE)
}

```

```{r plot_k_stats}
stats_frame <- data.frame(knn_stats)
colnames(stats_frame) <- c("k","accuracy","sensitivity","specificity")
for_plot <- reshape2::melt(stats_frame,id.var='k')
for_plot %>% ggplot(aes(x=k,y=value,col=variable)) + 
  geom_line() +
  xlab('k') +
  ylab('percent') +
  ggtitle('Performance of Classifier by K')
knn_stats
stats_frame
for_plot
```

```{r choose_k}
combined_stats <- stats_frame %>% 
  mutate(sums = accuracy + sensitivity + specificity) 
best_k_acc  <- which.max(combined_stats$accuracy)
best_k_sens <- which.max(combined_stats$sensitivity)
best_k_spec <- which.max(combined_stats$specificity)
best_k_combined <- which.max(combined_stats$sums)
chosen_k = best_k_combined
best_acc <-  round(100*combined_stats$accuracy[chosen_k])
best_sens <- round(100*combined_stats$sensitivity[chosen_k])
best_spec <- round(100*combined_stats$specificity[chosen_k])
```

k of `r best_k_acc`  is best for accuracy.

k of `r best_k_sens` is best for sensitivity.

k of `r best_k_spec` is best for specificity.

we choose `r chosen_k` as best overall, since it gives the
highest sum of accuracy, sensitivity, and specificity.

```{r knn_pred}
knn_pred <- knn(normalized[,cols_for_knn],
                normalized[,cols_for_knn],
                normalized$Attrition,k=chosen_k)
CM_knn = confusionMatrix(table(as.factor(normalized$Attrition),knn_pred),positive=positive_value)
knn_acc <- CM_knn$overall[1] # accuracy
knn_sens <- CM_knn$byClass[1] # sensitivity
knn_spec <- CM_knn$byClass[2] # specificity
```

KNN accuracy turns out to be `r format(100*knn_acc,digits=2)` %.

KNN sensitivity is `r format(100*knn_sens,digits=2)` %.

KNN specificity is `r format(100*knn_spec,digits=2)` %.

```





