---
title: "Salary Prediction"
author: "R.M. Palmer"
date: "11/18/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(caret)
library(leaps)
library(MASS)
library(relaimpo)
library(car)
library(glmnet)
```

```{r child = 'dataload.Rmd'}
```

```{r lm_common}
all_predictors <- formula(MonthlyIncome ~
                            Age +
                            BusinessTravel +
                            Department +
                            DistanceFromHome +
                            Education +
                            EducationField +
                            EnvironmentSatisfaction +
                            Gender +
                            JobInvolvement +
                            JobLevel +
                            JobRole +
                            JobSatisfaction +
                            MaritalStatus +
                            NumCompaniesWorked +
                            PercentSalaryHike +
                            PerformanceRating +
                            RelationshipSatisfaction +
                            StockOptionLevel +
                            TotalWorkingYears +
                            TrainingTimesLastYear +
                            WorkLifeBalance +
                            YearsAtCompany +
                            YearsInCurrentRole +
                            YearsSinceLastPromotion +
                            YearsWithCurrManager)

sensible_predictors <- formula(MonthlyIncome ~
                            Age +
                            BusinessTravel +
                            Department +
                            Education +
                            EducationField +
                            Gender +
                            JobLevel +
                            JobRole +
                            MaritalStatus +
                            PerformanceRating +
                            StockOptionLevel +
                            TotalWorkingYears +
                            TrainingTimesLastYear +
                            YearsAtCompany +
                            YearsInCurrentRole)

few_predictors <- formula(MonthlyIncome ~
                            Age +
                            Department +
                            Education +
                            EducationField +
                            Gender +
                            JobLevel +
                            JobRole +
                            PerformanceRating +
                            TotalWorkingYears +
                            YearsAtCompany )

numeric_predictors <- formula(MonthlyIncome ~
                            Age +
                            DistanceFromHome +
                            Education +
                            EnvironmentSatisfaction +
                            JobInvolvement +
                            JobLevel +
                            JobSatisfaction +
                            NumCompaniesWorked +
                            PercentSalaryHike +
                            PerformanceRating +
                            RelationshipSatisfaction +
                            StockOptionLevel +
                            TotalWorkingYears +
                            TrainingTimesLastYear +
                            WorkLifeBalance +
                            YearsAtCompany +
                            YearsInCurrentRole +
                            YearsSinceLastPromotion +
                            YearsWithCurrManager)

factor_predictors <- formula(MonthlyIncome ~ 
                            BusinessTravel +
                            Department +
                            EducationField +
                            Gender +
                            JobRole +
                            MaritalStatus  )

dummy_predictors  <- formula(q ~ 
                            BusinessTravel +
                            Department +
                            EducationField +
                            Gender +
                            JobRole +
                            MaritalStatus  )

```

```{r only_factors}
factor_fit <- lm(factor_predictors, data=employee_data)
stepwise_factor <- stepAIC(factor_fit,direction="both")
stepwise_factor$anova

dummy <- employee_data %>% mutate(q=as.numeric(Attrition))
factor_fit <- lm(dummy_predictors, data=dummy)
stepwise_factor <- stepAIC(factor_fit,direction="both")
stepwise_factor$anova

```

```{r stepwise}
all_fit <- lm(all_predictors,data=employee_data)
stepwise <- stepAIC(all_fit,direction="both")
stepwise$anova
```

## job level seems most important,  Perhaps do separate analysis for each job level

```{r pick_numeric}
num_fit <- lm(numeric_predictors,data=employee_data)
stepwise_numeric <- stepAIC(num_fit, direction = "both")

calc.relimp(stepwise_numeric,type=c("lmg","last","first","pratt"),
   rela=TRUE)

# Bootstrap Measures of Relative Importance (1000 samples) 
boot <- boot.relimp(stepwise_numeric, b = 1000, type = c("lmg", 
  "last", "first", "pratt"), rank = TRUE, 
  diff = TRUE, rela = TRUE)
booteval.relimp(boot) # print result
plot(booteval.relimp(boot,sort=TRUE)) # plot result
```

```{r allsubsets}
#leaps <- regsubsets(numeric_predictors,data=employee_data,nbest=5)
#summary(leaps)
#plot(leaps,scale="r2")
#subsets(leaps,statistic="rsq")
```

```{r lasso}
x_vars <- model.matrix(all_predictors, employee_data)[,-1]
y_var <- employee_data$MonthlyIncome
lambda_seq <- 10^seq(2, -2, by = -.1)

# Splitting the data into test and train
set.seed(42)
train_frac <- 0.7
trainIndices = sample(1:dim(employee_data)[1],round(train_frac * dim(employee_data)[1]))
test_x = (-trainIndices)
test_y = y_var[test_x]

cv_output <- cv.glmnet(x_vars[trainIndices,], y_var[trainIndices], 
            alpha = 1, lambda = lambda_seq)

# identifying best lamda
best_lam <- cv_output$lambda.min

# Rebuilding the model with best lamda value identified
lasso_best <- glmnet(x_vars[trainIndices,], y_var[trainIndices], alpha = 1, lambda = best_lam)
coef(lasso_best)
```

```{r loocv}
train_control <- trainControl(method="LOOCV")
salary_loocv <- train(MonthlyIncome ~ YearsWithCurrManager
                        +YearsSinceLastPromotion
                        +TotalWorkingYears
                        +JobRole
                        +JobLevel
                        +JobInvolvement
                        +Gender
                        +Education
                        +EducationField
                        +BusinessTravel,
                      data=employee_data,
                      method="lm",trControl = train_control)
print(salary_loocv)
```