---
title: "Model Selection"
author: "R.M. Palmer"
date: "11/18/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(relaimpo)
library(MASS)
```

```{r child = 'dataload.Rmd'}
```

```{r regression_common}
numeric_predictors <- c("Age",
"t_DistanceFromHome",
"t_Education",
"t_EnvironmentSatisfaction",
"t_JobInvolvement",
"t_JobLevel",
"t_JobSatisfaction",
"t_NumCompaniesWorked",
"t_PercentSalaryHike",
"t_PerformanceRating",
"t_RelationshipSatisfaction",
"t_StockOptionLevel",
"t_TotalWorkingYears",
"t_TrainingTimesLastYear",
"t_WorkLifeBalance",
"t_YearsAtCompany",
"t_YearsInCurrentRole",
"t_YearsSinceLastPromotion",
"t_YearsWithCurrManager")

factor_predictors <- c("BusinessTravel",
"Department",
"EducationField",
"Gender",
"JobRole",
"MaritalStatus")


att_f_all <- as.formula(paste("numeric_attrition ~ ",
                             paste(numeric_predictors,collapse="+"),
                             " * ",
                             paste(factor_predictors,collapse="*")
                             ))

att_f_num <- as.formula(paste("numeric_attrition ~ ",paste(numeric_predictors,collapse="+")))
att_f_fac <- as.formula(paste("numeric_attrition ~ ",paste(factor_predictors,collapse="+")))
```

```{r stepwise_selection_att}
att_fit <- lm(att_f_all, data=employee_data)
stepwise_att <- stepAIC(att_fit,direction="both")
#stepwise_att$anova
stepwise_att$call
```

```{r relimp_att}
att_fit_relimp <- calc.relimp(att_fit,type="last")
att_fit_ranking <- sort(att_fit_relimp$last.rank)
att_fit_top3 <- att_fit_ranking[1:3]
```

From the relaimpo package,  
The most important predictors for attrition are `r names(att_fit_top3)`  
The complete list is `r names(att_fit_ranking)`

```{r select_knn_predictors}
knn_fit <- lm(att_f_num, data=employee_data)
stepwise_knn <- stepAIC(knn_fit,direction="both")
#stepwise_knn$anova
stepwise_knn$call
```