---
title: "Model Selection"
author: "R.M. Palmer"
date: "11/18/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(caret)
library(leaps)
library(MASS)
library(relaimpo)
library(car)
library(glmnet)
```

```{r child = 'dataload.Rmd'}
```

```{r regression_common}
numeric_predictors <- c("Age",
"DistanceFromHome",
"Education",
"EnvironmentSatisfaction",
"JobInvolvement",
"JobLevel",
"JobSatisfaction",
"NumCompaniesWorked",
"PercentSalaryHike",
"PerformanceRating",
"RelationshipSatisfaction",
"StockOptionLevel",
"TotalWorkingYears",
"TrainingTimesLastYear",
"WorkLifeBalance",
"YearsAtCompany",
"YearsInCurrentRole",
"YearsSinceLastPromotion",
"YearsWithCurrManager")

factor_predictors <- c("BusinessTravel",
"Department",
"EducationField",
"Gender",
"JobRole",
"MaritalStatus")

all_predictors <- c(factor_predictors,numeric_predictors)

# income as a function of various sets of predictors
mi_f_all <- as.formula(paste("MonthlyIncome ~ ",paste(all_predictors,collapse="+")
mi_f_num <- as.formula(paste("MonthlyIncome ~ ",paste(numeric_predictors,collapse="+")
mi_f_fac <- as.formula(paste("MonthlyIncome ~ ",paste(factor_predictors,collapse="+")

# numeric attribution as a function of various sets of predictors
att_f_all <- as.formula(paste("numeric_attrition ~ ",paste(all_predictors,collapse="+")
att_f_num <- as.formula(paste("numeric_attrition ~ ",paste(numeric_predictors,collapse="+")
att_f_fac <- as.formula(paste("numeric_attrition ~ ",paste(factor_predictors,collapse="+")
```

```{r stepwise_selection}
mi_fit <- lm(mi_f_all, data=employee_data)
stepwise_mi <- stepAIC(mi_fit,direction="both")
stepwise_mi$anova

att_fit <- lm(att_f_all, data=employee_data)
stepwise_att <- stepAIC(att_fit,direction="both")
stepwise_att$anova

```

```{r pick_numeric}
num_fit <- lm(numeric_predictors,data=employee_data)
stepwise_numeric <- stepAIC(num_fit, direction = "both")

calc.relimp(stepwise_numeric,type=c("lmg","last","first","pratt"),
   rela=TRUE)

# Bootstrap Measures of Relative Importance (1000 samples) 
boot <- boot.relimp(stepwise_numeric, b = 1000, type = c("lmg", 
  "last", "first", "pratt"), rank = TRUE, 
  diff = TRUE, rela = TRUE)
booteval.relimp(boot) # print result
plot(booteval.relimp(boot,sort=TRUE)) # plot result
```

```{r allsubsets}
#leaps <- regsubsets(numeric_predictors,data=employee_data,nbest=5)
#summary(leaps)
#plot(leaps,scale="r2")
#subsets(leaps,statistic="rsq")
```

```{r lasso}
x_vars <- model.matrix(all_predictors, employee_data)[,-1]
y_var <- employee_data$MonthlyIncome
lambda_seq <- 10^seq(2, -2, by = -.1)

# Splitting the data into test and train
set.seed(42)
train_frac <- 0.7
trainIndices = sample(1:dim(employee_data)[1],round(train_frac * dim(employee_data)[1]))
test_x = (-trainIndices)
test_y = y_var[test_x]

cv_output <- cv.glmnet(x_vars[trainIndices,], y_var[trainIndices], 
            alpha = 1, lambda = lambda_seq)

# identifying best lamda
best_lam <- cv_output$lambda.min

# Rebuilding the model with best lamda value identified
lasso_best <- glmnet(x_vars[trainIndices,], y_var[trainIndices], alpha = 1, lambda = best_lam)
coef(lasso_best)
```

```{r loocv}
train_control <- trainControl(method="LOOCV")
salary_loocv <- train(MonthlyIncome ~ YearsWithCurrManager
                        +YearsSinceLastPromotion
                        +TotalWorkingYears
                        +JobRole
                        +JobLevel
                        +JobInvolvement
                        +Gender
                        +Education
                        +EducationField
                        +BusinessTravel,
                      data=employee_data,
                      method="lm",trControl = train_control)
print(salary_loocv)
```